CREATE TABLE IF NOT EXISTS dragon_tiger_billboards (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  trade_id VARCHAR(64) NOT NULL,
  trade_date DATE NOT NULL,
  security_code VARCHAR(10) NOT NULL,
  security_name VARCHAR(64) NOT NULL,
  exchange VARCHAR(4) NOT NULL,
  explanation VARCHAR(500) NULL,
  change_type VARCHAR(32) NULL,
  net_buy_amt DOUBLE NULL,
  buy_amt DOUBLE NULL,
  sell_amt DOUBLE NULL,
  billboard_deal_amt DOUBLE NULL,
  close_price DOUBLE NULL,
  change_pct DOUBLE NULL,
  turnover_rate DOUBLE NULL,
  reason_codes JSON NULL,
  source_key VARCHAR(32) NOT NULL DEFAULT 'eastmoney',
  source_fingerprint CHAR(64) NOT NULL,
  fetched_at DATETIME(3) NOT NULL,
  UNIQUE INDEX idx_dtb_fingerprint (source_fingerprint),
  UNIQUE INDEX idx_dtb_source_trade (source_key, trade_id),
  INDEX idx_dtb_date (trade_date),
  INDEX idx_dtb_code_date (security_code, trade_date),
  INDEX idx_dtb_net_buy (trade_date, net_buy_amt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dragon_tiger_seats (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  billboard_id BIGINT UNSIGNED NOT NULL,
  trade_id VARCHAR(64) NOT NULL,
  trade_date DATE NOT NULL,
  security_code VARCHAR(10) NOT NULL,
  seat_name VARCHAR(255) NOT NULL,
  seat_side VARCHAR(8) NOT NULL,
  operate_dept_code VARCHAR(64) NULL,
  buy_amt DOUBLE NULL,
  sell_amt DOUBLE NULL,
  net_amt DOUBLE NULL,
  seat_rank INT UNSIGNED NOT NULL,
  is_institutional TINYINT(1) NOT NULL DEFAULT 0,
  source_key VARCHAR(32) NOT NULL DEFAULT 'eastmoney',
  source_fingerprint CHAR(64) NOT NULL,
  fetched_at DATETIME(3) NOT NULL,
  UNIQUE INDEX idx_dts_fingerprint (source_fingerprint),
  INDEX idx_dts_billboard (billboard_id),
  INDEX idx_dts_date_code (trade_date, security_code),
  INDEX idx_dts_seat (seat_name),
  INDEX idx_dts_date_seat (trade_date, seat_name),
  CONSTRAINT fk_dts_billboard FOREIGN KEY (billboard_id)
    REFERENCES dragon_tiger_billboards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
