CREATE TABLE IF NOT EXISTS market_news (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  news_id VARCHAR(128) NOT NULL,
  source_key VARCHAR(32) NOT NULL,
  source_name VARCHAR(64) NOT NULL,
  source_tier VARCHAR(16) NOT NULL,
  content_type VARCHAR(16) NOT NULL,
  source_url VARCHAR(1024) NULL,
  title VARCHAR(500) NOT NULL,
  summary TEXT NULL,
  content TEXT NULL,
  published_at DATETIME(3) NOT NULL,
  security_code VARCHAR(10) NULL,
  security_name VARCHAR(64) NULL,
  industry VARCHAR(64) NULL,
  tags JSON NULL,
  raw JSON NULL,
  canonical_hash CHAR(64) NOT NULL,
  fetched_at DATETIME(3) NOT NULL,
  UNIQUE INDEX idx_mn_news_source (news_id, source_key),
  INDEX idx_mn_canonical (canonical_hash, published_at),
  INDEX idx_mn_published (published_at, id),
  INDEX idx_mn_tier (source_tier, published_at),
  INDEX idx_mn_source (source_key, published_at),
  INDEX idx_mn_code (security_code, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
