CREATE TABLE IF NOT EXISTS financial_reports (
  instrument_key INT UNSIGNED NOT NULL,
  report_period DATE NOT NULL,
  announcement_date DATE NOT NULL,
  report_type VARCHAR(16) NOT NULL DEFAULT 'quarterly',
  fiscal_year SMALLINT UNSIGNED NOT NULL,
  fiscal_quarter TINYINT UNSIGNED NOT NULL,
  update_flag TINYINT UNSIGNED NOT NULL DEFAULT 0,

  total_revenue DOUBLE NULL,
  revenue DOUBLE NULL,
  operating_cost DOUBLE NULL,
  total_operating_cost DOUBLE NULL,
  operating_profit DOUBLE NULL,
  total_profit DOUBLE NULL,
  income_tax DOUBLE NULL,
  net_profit DOUBLE NULL,
  net_profit_parent DOUBLE NULL,

  total_assets DOUBLE NULL,
  total_liabilities DOUBLE NULL,
  total_equity DOUBLE NULL,
  equity_parent DOUBLE NULL,
  total_current_assets DOUBLE NULL,
  total_current_liabilities DOUBLE NULL,
  cash_and_equivalents DOUBLE NULL,
  accounts_receivable DOUBLE NULL,
  inventory DOUBLE NULL,
  goodwill DOUBLE NULL,
  short_term_borrowings DOUBLE NULL,
  long_term_borrowings DOUBLE NULL,
  bonds_payable DOUBLE NULL,

  net_operating_cash_flow DOUBLE NULL,
  net_investing_cash_flow DOUBLE NULL,
  net_financing_cash_flow DOUBLE NULL,
  capital_expenditure DOUBLE NULL,
  free_cash_flow DOUBLE NULL,

  eps DOUBLE NULL,
  diluted_eps DOUBLE NULL,
  bps DOUBLE NULL,
  revenue_per_share DOUBLE NULL,
  operating_cash_flow_per_share DOUBLE NULL,
  roe_pct DOUBLE NULL,
  roe_weighted_pct DOUBLE NULL,
  roe_diluted_pct DOUBLE NULL,
  roe_calculated_pct DOUBLE NULL,
  roe_calculation_method VARCHAR(64) NULL,
  roa_pct DOUBLE NULL,
  gross_margin_pct DOUBLE NULL,
  net_margin_pct DOUBLE NULL,
  debt_to_assets_pct DOUBLE NULL,
  current_ratio DOUBLE NULL,
  quick_ratio DOUBLE NULL,
  asset_turnover DOUBLE NULL,
  inventory_turnover DOUBLE NULL,
  receivables_turnover DOUBLE NULL,
  operating_cash_flow_to_revenue_pct DOUBLE NULL,
  revenue_yoy_pct DOUBLE NULL,
  net_profit_yoy_pct DOUBLE NULL,

  source_key VARCHAR(32) NOT NULL,
  source_version VARCHAR(64) NOT NULL,
  source_fingerprint CHAR(64) NOT NULL,
  fetched_at DATETIME(3) NOT NULL,

  PRIMARY KEY (instrument_key, report_period, announcement_date),
  UNIQUE KEY idx_fr_source_fingerprint (source_fingerprint),
  KEY idx_fr_period (report_period),
  KEY idx_fr_announcement (announcement_date),
  KEY idx_fr_instrument_announcement (instrument_key, announcement_date),
  KEY idx_fr_source_fetched (source_key, fetched_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
