// Generated by scripts/generate-strategy-capabilities.mjs. Do not edit by hand.
// Sources: src/features/indicators/registry.ts and src/features/visualStrategies/types.ts
export const GENERATED_VISUAL_INDICATOR_CAPABILITIES = [
  {
    "id": "sma",
    "name": "SMA 简单移动平均",
    "params": [
      {
        "name": "period1",
        "label": "周期 1",
        "defaultValue": 5,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period2",
        "label": "周期 2",
        "defaultValue": 10,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period3",
        "label": "周期 3",
        "defaultValue": 20,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period4",
        "label": "周期 4",
        "defaultValue": 60,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period5",
        "label": "周期 5",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period6",
        "label": "周期 6",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period7",
        "label": "周期 7",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period8",
        "label": "周期 8",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "sma1",
        "label": "SMA"
      },
      {
        "key": "sma2",
        "label": "SMA"
      },
      {
        "key": "sma3",
        "label": "SMA"
      },
      {
        "key": "sma4",
        "label": "SMA"
      },
      {
        "key": "sma5",
        "label": "SMA"
      },
      {
        "key": "sma6",
        "label": "SMA"
      },
      {
        "key": "sma7",
        "label": "SMA"
      },
      {
        "key": "sma8",
        "label": "SMA"
      }
    ]
  },
  {
    "id": "ema",
    "name": "EMA 指数移动平均",
    "params": [
      {
        "name": "period1",
        "label": "周期 1",
        "defaultValue": 5,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period2",
        "label": "周期 2",
        "defaultValue": 10,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period3",
        "label": "周期 3",
        "defaultValue": 20,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period4",
        "label": "周期 4",
        "defaultValue": 60,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period5",
        "label": "周期 5",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period6",
        "label": "周期 6",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period7",
        "label": "周期 7",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      },
      {
        "name": "period8",
        "label": "周期 8",
        "defaultValue": 0,
        "min": 0,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "ema1",
        "label": "EMA"
      },
      {
        "key": "ema2",
        "label": "EMA"
      },
      {
        "key": "ema3",
        "label": "EMA"
      },
      {
        "key": "ema4",
        "label": "EMA"
      },
      {
        "key": "ema5",
        "label": "EMA"
      },
      {
        "key": "ema6",
        "label": "EMA"
      },
      {
        "key": "ema7",
        "label": "EMA"
      },
      {
        "key": "ema8",
        "label": "EMA"
      }
    ]
  },
  {
    "id": "boll",
    "name": "BOLL 布林带",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 20,
        "min": 2,
        "max": 500,
        "step": 1
      },
      {
        "name": "stdDev",
        "label": "标准差倍数",
        "defaultValue": 2,
        "min": 0.5,
        "max": 5,
        "step": 0.1
      }
    ],
    "outputs": [
      {
        "key": "upper",
        "label": "上轨"
      },
      {
        "key": "middle",
        "label": "中轨"
      },
      {
        "key": "lower",
        "label": "下轨"
      }
    ]
  },
  {
    "id": "macd",
    "name": "MACD 指数平滑异同",
    "params": [
      {
        "name": "fast",
        "label": "快线周期",
        "defaultValue": 12,
        "min": 2,
        "max": 500,
        "step": 1
      },
      {
        "name": "slow",
        "label": "慢线周期",
        "defaultValue": 26,
        "min": 2,
        "max": 500,
        "step": 1
      },
      {
        "name": "signal",
        "label": "信号线周期",
        "defaultValue": 9,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "dif",
        "label": "DIF"
      },
      {
        "key": "dea",
        "label": "DEA"
      },
      {
        "key": "histogram",
        "label": "柱"
      }
    ]
  },
  {
    "id": "rsi",
    "name": "RSI 相对强弱",
    "params": [
      {
        "name": "period1",
        "label": "RSI1 周期",
        "defaultValue": 6,
        "min": 2,
        "max": 500,
        "step": 1
      },
      {
        "name": "period2",
        "label": "RSI2 周期",
        "defaultValue": 12,
        "min": 2,
        "max": 500,
        "step": 1
      },
      {
        "name": "period3",
        "label": "RSI3 周期",
        "defaultValue": 24,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "rsi1",
        "label": "RSI1"
      },
      {
        "key": "rsi2",
        "label": "RSI2"
      },
      {
        "key": "rsi3",
        "label": "RSI3"
      }
    ]
  },
  {
    "id": "kdj",
    "name": "KDJ 随机指标",
    "params": [
      {
        "name": "n",
        "label": "RSV 周期",
        "defaultValue": 9,
        "min": 2,
        "max": 500,
        "step": 1
      },
      {
        "name": "m1",
        "label": "K 平滑",
        "defaultValue": 3,
        "min": 2,
        "max": 100,
        "step": 1
      },
      {
        "name": "m2",
        "label": "D 平滑",
        "defaultValue": 3,
        "min": 2,
        "max": 100,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "k",
        "label": "K"
      },
      {
        "key": "d",
        "label": "D"
      },
      {
        "key": "j",
        "label": "J"
      }
    ]
  },
  {
    "id": "atr",
    "name": "ATR 平均真实波幅",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 14,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "atr",
        "label": "ATR"
      }
    ]
  },
  {
    "id": "cci",
    "name": "CCI 商品通道",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 20,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "cci",
        "label": "CCI"
      }
    ]
  },
  {
    "id": "wr",
    "name": "WR 威廉指标",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 10,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "wr",
        "label": "WR"
      }
    ]
  },
  {
    "id": "obv",
    "name": "OBV 能量潮",
    "params": [],
    "outputs": [
      {
        "key": "obv",
        "label": "OBV"
      }
    ]
  },
  {
    "id": "volumeMa",
    "name": "成交量均线",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 20,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "volumeMa",
        "label": "量均线"
      }
    ]
  },
  {
    "id": "volume",
    "name": "成交量",
    "params": [
      {
        "name": "period",
        "label": "均量周期",
        "defaultValue": 20,
        "min": 1,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "volume",
        "label": "成交量"
      },
      {
        "key": "volumeAverage",
        "label": "平均成交量"
      },
      {
        "key": "volumeRatio",
        "label": "量比"
      }
    ]
  },
  {
    "id": "highLowBreakout",
    "name": "高低点突破",
    "params": [
      {
        "name": "period",
        "label": "回看周期",
        "defaultValue": 20,
        "min": 1,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "previousHigh",
        "label": "前期高点"
      },
      {
        "key": "previousLow",
        "label": "前期低点"
      }
    ]
  },
  {
    "id": "drawdown",
    "name": "回撤",
    "params": [
      {
        "name": "period",
        "label": "峰值周期",
        "defaultValue": 60,
        "min": 1,
        "max": 1000,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "peak",
        "label": "区间峰值"
      },
      {
        "key": "drawdown",
        "label": "回撤率"
      }
    ]
  },
  {
    "id": "bias",
    "name": "BIAS 均线乖离率",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 20,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "bias",
        "label": "BIAS"
      }
    ]
  },
  {
    "id": "volatility",
    "name": "波动率",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 20,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "volatility",
        "label": "波动率"
      },
      {
        "key": "annualVolatility",
        "label": "年化波动率"
      }
    ]
  },
  {
    "id": "volCluster",
    "name": "波动聚集",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 20,
        "min": 2,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "volCluster",
        "label": "波动聚集"
      }
    ]
  },
  {
    "id": "hold",
    "name": "HOLD 买入持有收益",
    "params": [],
    "outputs": [
      {
        "key": "holdReturn",
        "label": "HOLD收益"
      },
      {
        "key": "holdNav",
        "label": "HOLD净值"
      }
    ]
  },
  {
    "id": "reversal",
    "name": "反转因子",
    "params": [
      {
        "name": "period",
        "label": "周期",
        "defaultValue": 20,
        "min": 1,
        "max": 500,
        "step": 1
      }
    ],
    "outputs": [
      {
        "key": "reversal",
        "label": "反转"
      }
    ]
  }
] as const;

export const GENERATED_MARKET_FIELDS = ["open","high","low","close","volume"] as const;
export const GENERATED_ACCOUNT_FIELDS = ["hasPosition","holdingDays","unrealizedPnlPercent"] as const;
export const GENERATED_COMPARE_OPERATORS = ["gt","gte","lt","lte","eq","crossesAbove","crossesBelow","between"] as const;
export const GENERATED_RISK_RULE_TYPES = ["stopLoss","takeProfit","trailingStop","maxHoldingDays","lossStreakCooldown"] as const;
