SELECT tradeDate,
       symbol,
       name,
       market,
       signalType,
       signalTime,
       entryTime,
       exitTime,
       entryPrice,
       exitPrice,
       grossReturn,
       netReturn,
       momentum5,
       momentum15,
       momentum30,
       rollingAmplitude30,
       intradayAmplitude,
       tailMomentum,
       signalStrength,
       dailySignalRank,
       averageAmount20,
       totalMarketCap,
       floatMarketCap,
       peTtm,
       pb,
       filterDataDate,
       roundTripCostBps
FROM intraday_trading_signals
ORDER BY symbol, tradeDate, signalTime;
