SELECT signalMonth,
       signalDate,
       entryDate,
       exitDate,
       selectionRank,
       market,
       symbol,
       name,
       level1Code,
       level1Name,
       averageAmount20,
       peTtm,
       pb,
       earningsYield,
       bookYield,
       momentum12m1m,
       trailingDividendEventCount,
       trailingCashDividendPerShare,
       trailingDividendYield,
       earningsYieldNeutralScore,
       bookYieldNeutralScore,
       valueScore,
       momentumNeutralScore,
       dividendNeutralScore,
       compositeScore,
       entryAdjustedOpen,
       exitAdjustedOpen,
       adjustedMonthlyReturn,
       factorVersion
FROM multifactor_results
WHERE selected
ORDER BY signalMonth, selectionRank;
