SELECT signalMonth,
       signalDate,
       rotationRank,
       indexCode,
       industryCode,
       industryName,
       stockCount,
       validPeCount,
       validPbCount,
       dividendStockCount,
       industryMarketCap,
       weightedPe,
       weightedPb,
       weightedDividendYield,
       pePercentile,
       pbPercentile,
       dividendYieldPercentile,
       momentum3m,
       momentum6m,
       momentum3Percentile,
       momentum6Percentile,
       compositeScore,
       monthlyIndustryReturn
FROM sw_industry_rotation_scores
ORDER BY signalMonth, rotationRank;
