export const ErrorCodes = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATASET_NOT_FOUND: 'DATASET_NOT_FOUND',
  RESULT_NOT_FOUND: 'RESULT_NOT_FOUND',
  STRATEGY_NOT_FOUND: 'STRATEGY_NOT_FOUND',
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  DUPLICATE_CHECKSUM: 'DUPLICATE_CHECKSUM',
  DB_UNAVAILABLE: 'DB_UNAVAILABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  // Phase 5
  INSTRUMENT_NOT_FOUND: 'INSTRUMENT_NOT_FOUND',
  SYNC_JOB_NOT_FOUND: 'SYNC_JOB_NOT_FOUND',
  SYNC_IN_PROGRESS: 'SYNC_IN_PROGRESS',
  PROVIDER_ERROR: 'PROVIDER_ERROR',
  QUALITY_ISSUE_NOT_FOUND: 'QUALITY_ISSUE_NOT_FOUND',
  EXPERIMENT_VERSION_NOT_FOUND: 'EXPERIMENT_VERSION_NOT_FOUND',
  EXPERIMENT_RUN_NOT_FOUND: 'EXPERIMENT_RUN_NOT_FOUND',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  INVALID_EXPERIMENT_STATE: 'INVALID_EXPERIMENT_STATE',
  RESULT_HASH_MISMATCH: 'RESULT_HASH_MISMATCH',
  RESULT_BINDING_MISMATCH: 'RESULT_BINDING_MISMATCH',
  VALIDATION_PLAN_NOT_FOUND: 'VALIDATION_PLAN_NOT_FOUND',
  LOCKED_TEST_ALREADY_OPENED: 'LOCKED_TEST_ALREADY_OPENED',
  LOCKED_TEST_BINDING_MISMATCH: 'LOCKED_TEST_BINDING_MISMATCH',
  EXPERIMENT_REPORT_NOT_FOUND: 'EXPERIMENT_REPORT_NOT_FOUND',
  EXPERIMENT_ARTIFACT_JOB_NOT_FOUND: 'EXPERIMENT_ARTIFACT_JOB_NOT_FOUND',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiErrorResponse {
  error: string;
  message: string;
  details?: unknown;
}

export function apiError(
  code: ErrorCode,
  message: string,
  details?: unknown,
): ApiErrorResponse {
  return { error: code, message, details };
}

export function dbUnavailable(): ApiErrorResponse {
  return apiError(
    ErrorCodes.DB_UNAVAILABLE,
    '数据库服务不可用，请稍后重试',
  );
}
