import type { FactorDefinition } from './schema.js';

export const BUILTIN_FACTORS: FactorDefinition[] = [
  {
    id: 'momentum_20',
    name: '20 日动量',
    description: '收盘价相对 20 个交易日前收盘价的涨跌幅。',
    direction: 'higher-is-better',
    dependencies: ['close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'momentum_20' },
  },
  {
    id: 'reversal_5',
    name: '5 日反转',
    description: '5 日涨幅取反，用于观察短期反转效应。',
    direction: 'higher-is-better',
    dependencies: ['close'],
    warmupDays: 5,
    expression: { type: 'builtin', id: 'reversal_5' },
  },
  {
    id: 'roc_10',
    name: '10 日价格变动速率',
    description: '当前收盘价相对 10 个交易日前收盘价的涨跌幅。',
    direction: 'higher-is-better',
    dependencies: ['close'],
    warmupDays: 10,
    expression: { type: 'builtin', id: 'roc_10' },
  },
  {
    id: 'roc_60',
    name: '60 日价格变动速率',
    description: '当前收盘价相对 60 个交易日前收盘价的涨跌幅。',
    direction: 'higher-is-better',
    dependencies: ['close'],
    warmupDays: 60,
    expression: { type: 'builtin', id: 'roc_60' },
  },
  {
    id: 'volatility_20',
    name: '20 日波动率',
    description: '20 日收盘价变异系数，衡量近期波动强度。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'volatility_20' },
  },
  {
    id: 'volatility_60',
    name: '60 日波动率',
    description: '60 日收盘价变异系数，衡量中期波动强度。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 60,
    expression: { type: 'builtin', id: 'volatility_60' },
  },
  {
    id: 'turnover_20',
    name: '20 日平均换手',
    description: '近 20 日换手率均值。',
    direction: 'research',
    dependencies: ['turnoverRatePct'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'turnover_20' },
  },
  {
    id: 'amount_20',
    name: '20 日平均成交额',
    description: '近 20 日成交额均值，用于观察流动性。',
    direction: 'higher-is-better',
    dependencies: ['amount'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'amount_20' },
  },
  {
    id: 'ma_deviation_20',
    name: '20 日均线偏离',
    description: '收盘价相对 20 日均线的偏离幅度。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'ma_deviation_20' },
  },
  {
    id: 'bias_5',
    name: '5 日乖离率',
    description: '收盘价相对 5 日均线的偏离幅度。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 5,
    expression: { type: 'builtin', id: 'bias_5' },
  },
  {
    id: 'bias_10',
    name: '10 日乖离率',
    description: '收盘价相对 10 日均线的偏离幅度。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 10,
    expression: { type: 'builtin', id: 'bias_10' },
  },
  {
    id: 'bias_60',
    name: '60 日乖离率',
    description: '收盘价相对 60 日均线的偏离幅度。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 60,
    expression: { type: 'builtin', id: 'bias_60' },
  },
  {
    id: 'boll_position_20',
    name: 'BOLL 20 位置',
    description: '收盘价相对 20 日均线和两倍标准差的位置。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'boll_position_20' },
  },
  {
    id: 'boll_width_20',
    name: 'BOLL 20 带宽',
    description: '20 日布林带上下轨宽度相对均线的比例，用于衡量波动收缩和扩张。',
    direction: 'research',
    dependencies: ['close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'boll_width_20' },
  },
  {
    id: 'atr_14',
    name: 'ATR 14',
    description: '近 14 日真实波幅均值。',
    direction: 'research',
    dependencies: ['high', 'low', 'previousClose'],
    warmupDays: 14,
    expression: { type: 'builtin', id: 'atr_14' },
  },
  {
    id: 'range_pct_20',
    name: '20 日振幅均值',
    description: '近 20 日日内振幅均值，使用 high/low/close 衡量短期价格摆动强度。',
    direction: 'research',
    dependencies: ['high', 'low', 'close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'range_pct_20' },
  },
  {
    id: 'range_pct_60',
    name: '60 日振幅均值',
    description: '近 60 日日内振幅均值，衡量中期价格摆动强度。',
    direction: 'research',
    dependencies: ['high', 'low', 'close'],
    warmupDays: 60,
    expression: { type: 'builtin', id: 'range_pct_60' },
  },
  {
    id: 'volume_ratio_20',
    name: '20 日量比',
    description: '当日成交量相对近 20 日平均成交量的倍数。',
    direction: 'research',
    dependencies: ['volume'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'volume_ratio_20' },
  },
  {
    id: 'volume_ratio_60',
    name: '60 日量比',
    description: '当日成交量相对近 60 日平均成交量的倍数。',
    direction: 'research',
    dependencies: ['volume'],
    warmupDays: 60,
    expression: { type: 'builtin', id: 'volume_ratio_60' },
  },
  {
    id: 'amihud_20',
    name: 'Amihud 20 非流动性',
    description: '近 20 日绝对收益率与成交额之比的均值，数值越高代表价格冲击越强。',
    direction: 'lower-is-better',
    dependencies: ['close', 'previousClose', 'amount'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'amihud_20' },
  },
  {
    id: 'gap_1',
    name: '隔夜跳空幅度',
    description: '当日开盘价相对前收盘价的涨跌幅。',
    direction: 'research',
    dependencies: ['open', 'previousClose'],
    warmupDays: 1,
    expression: { type: 'builtin', id: 'gap_1' },
  },
  {
    id: 'intraday_strength_1',
    name: '日内强弱位置',
    description: '收盘价在当日高低区间中的位置，衡量日内买卖力量。',
    direction: 'higher-is-better',
    dependencies: ['high', 'low', 'close'],
    warmupDays: 1,
    expression: { type: 'builtin', id: 'intraday_strength_1' },
  },
  {
    id: 'breakout_20',
    name: '20 日突破强度',
    description: '收盘价相对过去 20 日最高价的位置，用于观察向上突破程度。',
    direction: 'higher-is-better',
    dependencies: ['high', 'close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'breakout_20' },
  },
  {
    id: 'drawdown_20',
    name: '20 日回撤幅度',
    description: '收盘价相对过去 20 日最高价的回撤幅度。',
    direction: 'lower-is-better',
    dependencies: ['high', 'close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'drawdown_20' },
  },
  {
    id: 'max_return_20',
    name: '20 日最大日收益率',
    description: '近 20 日单日收益率的最大值。',
    direction: 'research',
    dependencies: ['close', 'previousClose'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'max_return_20' },
  },
  {
    id: 'downside_volatility_20',
    name: '20 日下行波动率',
    description: '近 20 日负收益率的样本标准差，用于观察下行风险。',
    direction: 'lower-is-better',
    dependencies: ['close', 'previousClose'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'downside_volatility_20' },
  },
  {
    id: 'vwap_deviation_20',
    name: '20 日成交均价偏离',
    description: '收盘价相对 20 日成交额加权价格的偏离幅度。',
    direction: 'research',
    dependencies: ['close', 'amount', 'volume'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'vwap_deviation_20' },
  },
  {
    id: 'price_volume_corr_20',
    name: '20 日量价相关性',
    description: '近 20 日日收益率与成交量的滚动相关系数。',
    direction: 'research',
    dependencies: ['close', 'previousClose', 'volume'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'price_volume_corr_20' },
  },
  {
    id: 'pvt_flow_20',
    name: '20 日价格成交量趋势',
    description: '近 20 日收益率乘成交量的累积值，用于刻画量价趋势。',
    direction: 'higher-is-better',
    dependencies: ['close', 'previousClose', 'volume'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'pvt_flow_20' },
  },
  {
    id: 'obv_flow_20',
    name: '20 日能量潮变化',
    description: '近 20 日按涨跌方向累加的成交量变化。',
    direction: 'higher-is-better',
    dependencies: ['close', 'previousClose', 'volume'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'obv_flow_20' },
  },
  {
    id: 'cmf_20',
    name: '20 日蔡金资金流',
    description: '近 20 日资金流量乘数按成交量加权后的资金流指标。',
    direction: 'higher-is-better',
    dependencies: ['high', 'low', 'close', 'volume'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'cmf_20' },
  },
  {
    id: 'mfi_14',
    name: '14 日资金流量指标',
    description: '使用典型价格和成交量构造的 14 日资金流相对强弱。',
    direction: 'research',
    dependencies: ['high', 'low', 'close', 'previousClose', 'volume'],
    warmupDays: 14,
    expression: { type: 'builtin', id: 'mfi_14' },
  },
  {
    id: 'rsi_14',
    name: '14 日相对强弱指标',
    description: '近 14 日上涨幅度和下跌幅度的相对强弱。',
    direction: 'research',
    dependencies: ['close', 'previousClose'],
    warmupDays: 14,
    expression: { type: 'builtin', id: 'rsi_14' },
  },
  {
    id: 'psy_12',
    name: '12 日心理线',
    description: '近 12 日上涨天数占比。',
    direction: 'research',
    dependencies: ['close', 'previousClose'],
    warmupDays: 12,
    expression: { type: 'builtin', id: 'psy_12' },
  },
  {
    id: 'imi_14',
    name: '14 日日内动量指数',
    description: '近 14 日阳线实体与阴线实体的相对强弱。',
    direction: 'research',
    dependencies: ['open', 'close'],
    warmupDays: 14,
    expression: { type: 'builtin', id: 'imi_14' },
  },
  {
    id: 'cci_20',
    name: '20 日商品通道指数',
    description: '典型价格相对 20 日均值的偏离程度。',
    direction: 'research',
    dependencies: ['high', 'low', 'close'],
    warmupDays: 20,
    expression: { type: 'builtin', id: 'cci_20' },
  },
  {
    id: 'vhf_28',
    name: '28 日垂直水平滤波',
    description: '28 日最高最低价差与逐日价格变动总和的比率，用于区分趋势和震荡。',
    direction: 'research',
    dependencies: ['high', 'low', 'close', 'previousClose'],
    warmupDays: 28,
    expression: { type: 'builtin', id: 'vhf_28' },
  },
  {
    id: 'body_ratio_1',
    name: '实体占比',
    description: 'K 线实体占全天振幅的比例。',
    direction: 'research',
    dependencies: ['open', 'high', 'low', 'close'],
    warmupDays: 1,
    expression: { type: 'builtin', id: 'body_ratio_1' },
  },
  {
    id: 'upper_shadow_ratio_1',
    name: '上影线占比',
    description: '上影线占全天振幅的比例，用于观察冲高回落压力。',
    direction: 'lower-is-better',
    dependencies: ['open', 'high', 'low', 'close'],
    warmupDays: 1,
    expression: { type: 'builtin', id: 'upper_shadow_ratio_1' },
  },
  {
    id: 'lower_shadow_ratio_1',
    name: '下影线占比',
    description: '下影线占全天振幅的比例，用于观察探底回升强度。',
    direction: 'higher-is-better',
    dependencies: ['open', 'high', 'low', 'close'],
    warmupDays: 1,
    expression: { type: 'builtin', id: 'lower_shadow_ratio_1' },
  },
  {
    id: 'stochastic_k_14',
    name: '14 日随机摆动值',
    description: '收盘价在 14 日最高最低区间中的位置。',
    direction: 'research',
    dependencies: ['high', 'low', 'close'],
    warmupDays: 14,
    expression: { type: 'builtin', id: 'stochastic_k_14' },
  },
  {
    id: 'williams_r_14',
    name: '14 日威廉指标',
    description: '收盘价相对 14 日最高最低区间的位置，常用于超买超卖观察。',
    direction: 'research',
    dependencies: ['high', 'low', 'close'],
    warmupDays: 14,
    expression: { type: 'builtin', id: 'williams_r_14' },
  },
];

const BUILTIN_BY_ID = new Map(BUILTIN_FACTORS.map((factor) => [factor.id, factor]));

export function getBuiltinFactor(id: string): FactorDefinition | null {
  return BUILTIN_BY_ID.get(id) ?? null;
}
