import { z } from 'zod';
import { isValidAiModelList } from './services/aiModelList.js';

const envSchema = z.object({
  // Database
  DB_HOST: z.string().default('127.0.0.1'),
  DB_PORT: z.string().default('3306'),
  DB_USER: z.string().default('root'),
  DB_PASSWORD: z.string().default(''),
  DB_NAME: z.string().default('quant_backtest'),

  // AI Strategy
  AI_STRATEGY_ENABLED: z.enum(['true', 'false']).default('false'),
  OPENAI_API_KEY: z.string().default(''),
  OPENAI_BASE_URL: z.string().default('https://api.openai.com/v1'),
  OPENAI_MODEL: z.string().default('deepseek-v4-flash').refine(isValidAiModelList, {
    message: 'OPENAI_MODEL 必须是以英文分号分隔的非空、无重复模型列表',
  }),
  OPENAI_TIMEOUT_MS: z.string().default('60000'),

  // Market Data
  MARKET_DATA_ENABLED: z.enum(['true', 'false']).default('false'),
  MARKET_DATA_PROVIDER: z.string().default('tencent'),
  MARKET_DATA_API_KEY: z.string().default(''),
  MARKET_DATA_BASE_URL: z.string().default(''),
  TUSHARE_TOKEN: z.string().default(''),
  INSTRUMENT_SYNC_ENABLED: z.enum(['true', 'false']).default('true'),
  INSTRUMENT_SYNC_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('15:20'),
  MARKET_DATA_SYNC_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('15:30'),
  SCHEDULE_SKIP_NON_TRADING_PERIODS: z.enum(['true', 'false']).default('true'),
  MARKET_DATA_INTRADAY_INTERVAL_MINUTES: z.string().default('30'),
  MARKET_INDEX_AUTO_UPDATE_ENABLED: z.enum(['true', 'false']).default('true'),
  MARKET_CN_INDEX_UPDATE_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('20:00'),
  MARKET_US_INDEX_UPDATE_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('05:00'),
  FINANCIAL_DATA_ENABLED: z.enum(['true', 'false']).default('true'),
  FINANCIAL_DATA_UPDATE_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('19:00'),
  FINANCIAL_DATA_LOOKBACK_DAYS: z.string().regex(/^\d+$/).default('21'),
  RESEARCH_SNAPSHOT_MORNING_RETRY_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('08:30'),
  RESEARCH_SNAPSHOT_UPDATE_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('18:00'),
  RESEARCH_SNAPSHOT_RETRY_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('18:30'),
  MINUTE_DATA_UPDATE_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('16:30'),
  MINUTE_DATA_RETRY_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('17:30'),
  DRAGON_TIGER_ENABLED: z.enum(['true', 'false']).default('true'),
  DRAGON_TIGER_SYNC_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('18:00'),
  DRAGON_TIGER_RECHECK_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('18:30'),
  MARKET_NEWS_ENABLED: z.enum(['true', 'false']).default('true'),
  MARKET_NEWS_REFRESH_INTERVAL_MINUTES: z.string().regex(/^\d+$/).default('3'),
  MARKET_NEWS_RETENTION_DAYS: z.string().regex(/^\d+$/).default('3'),
  MARKET_OPINION_PUSH_ENABLED: z.enum(['true', 'false']).default('false'),
  MARKET_OPINION_MODEL: z.string().default(''),
  MARKET_OPINION_MORNING_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('09:00'),
  MARKET_OPINION_MIDDAY_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('12:00'),
  MARKET_OPINION_CLOSE_TIME: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).default('16:00'),
  MARKET_OPINION_PUSH_GRACE_MINUTES: z.string().regex(/^\d+$/).default('20'),
  MARKET_OPINION_PUSH_WEEKDAYS_ONLY: z.enum(['true', 'false']).default('true'),
  SMTP_HOST: z.string().default('smtp.163.com'),
  SMTP_PORT: z.string().regex(/^\d+$/).default('465'),
  SMTP_SECURE: z.enum(['true', 'false']).default('true'),
  SMTP_USER: z.string().default(''),
  SMTP_PASSWORD: z.string().default(''),
  MAIL_FROM: z.string().default(''),
  MAIL_TO: z.string().default(''),
  HISTORY_STORE_READ_MODE: z.enum(['legacy', 'prefer-v2', 'v2']).default('prefer-v2'),
  HISTORY_STORE_DUAL_WRITE: z.enum(['true', 'false']).default('true'),
  RESEARCH_SNAPSHOT_ROOT: z.string().default('./data/research-snapshots'),
  RESEARCH_SNAPSHOT_RETENTION_ENABLED: z.enum(['true', 'false']).default('true'),
  RESEARCH_SNAPSHOT_RETAIN_LATEST: z.string().regex(/^\d+$/).default('7'),
  RESEARCH_SNAPSHOT_RETAIN_DAILY_DAYS: z.string().regex(/^\d+$/).default('30'),
  RESEARCH_QUERY_MAX_ROWS: z.string().default('10000'),
  MINUTE_DATA_ZIP_ROOT: z.string().default('../../所有股票的历史数据/1m_price_zip'),
  MINUTE_DATA_ROOT: z.string().default('../../所有股票的历史数据/1m_price_parquet'),
  MINUTE_QUERY_MAX_ROWS: z.string().default('100000'),
  BACKUP_ROOT: z.string().default('./data/backups'),
  FACTOR_RESEARCH_ROOT: z.string().default('./data/factor-research'),
  FACTOR_MINER_PYTHON: z.string().default('python'),
  FACTOR_MINER_ROOT: z.string().default('../tools/factor-miner'),
  // 系统级硬上限；单个任务仍可在界面设置更短的超时。
  FACTOR_MINER_TIMEOUT_MS: z.string().default('21600000'),
  FACTOR_MINER_MAX_MEMORY_MB: z.string().default('4096'),

  // Operations admin console. Empty means the admin API is disabled.
  ADMIN_API_TOKEN: z.string().default(''),
  // Overview TTL cache (ms). 0 disables caching. See ADMIN_CONSOLE_OPTIMIZATION_PLAN §1.
  ADMIN_OVERVIEW_CACHE_TTL_MS: z.string().default('10000'),

  // Agent System
  AGENT_ENABLED: z.enum(['true', 'false']).default('false'),
  AGENT_PROVIDER: z.enum(['claude', 'codex']).default('claude'),
  AGENT_WSL_PROJECT_PATH: z.string().default(''),
  AGENT_CLAUDE_PATH: z.string().default('claude'),
  AGENT_CODEX_ENABLED: z.enum(['true', 'false']).default('false'),
  AGENT_CODEX_PATH: z.string().default('codex'),
  AGENT_CODEX_MODEL: z.string().default(''),
  AGENT_CODEX_WORKING_DIRECTORY: z.string().default(''),
  AGENT_CODEX_HOME: z.string().default(''),
  AGENT_CODEX_API_KEY: z.string().default(''),
  AGENT_CODEX_MODEL_PROVIDER: z.string().default(''),
  AGENT_CODEX_BASE_URL: z.string().default(''),
  AGENT_CODEX_MODEL_CATALOG: z.string().default(''),
  AGENT_CODEX_APPROVALS_ENABLED: z.enum(['true', 'false']).default('true'),
  AGENT_CODEX_APPROVAL_TIMEOUT_SECONDS: z.string().regex(/^\d+$/).default('300'),
  AGENT_CODEX_TOOLS_ENABLED: z.enum(['true', 'false']).default('true'),
  AGENT_CODEX_SANDBOX_MODE: z.enum(['read-only', 'workspace-write']).default('read-only'),
  AGENT_CODEX_WINDOWS_SANDBOX: z.enum(['elevated', 'unelevated']).default('unelevated'),
  AGENT_CODEX_NETWORK_ENABLED: z.enum(['true', 'false']).default('false'),
  AGENT_CODEX_MARKET_DATA_CLI: z.string().default(''),
  AGENT_CODEX_EXTERNAL_DATA_SKILL_ENABLED: z.enum(['true', 'false']).default('false'),
  AGENT_CODEX_PYTHON_PATH: z.string().default(''),
  AGENT_CODEX_TIMEOUT_MINUTES: z.string().regex(/^\d+$/).default('60'),
  AGENT_TIMEOUT_MINUTES: z.string().regex(/^\d+$/).default('60'),
  AGENT_MAX_CONCURRENT: z.string().regex(/^\d+$/).default('1'),
  AGENT_REPORT_ROOT: z.string().default('data/agent-reports'),
  AGENT_ATTACHMENT_ROOT: z.string().default('tmp_output/.agent-attachments'),
  AGENT_ATTACHMENT_MAX_FILE_MB: z.string().regex(/^\d+$/).default('20'),
  AGENT_ATTACHMENT_MAX_FILES: z.string().regex(/^\d+$/).default('8'),
  AGENT_ATTACHMENT_MAX_CONTEXT_CHARS: z.string().regex(/^\d+$/).default('300000'),

  PORT: z.string().default('3001'),
});

export type EnvConfig = z.infer<typeof envSchema>;

export function loadConfig(): EnvConfig {
  return envSchema.parse(process.env);
}
