// Generated by scripts/generate-multi-asset-capabilities.mjs. Do not edit by hand.
export const MULTI_ASSET_CAPABILITIES = {
  "protocolVersion": "1.0",
  "universes": [
    "index:000300",
    "index:000905",
    "all_a"
  ],
  "fundamentalFields": [
    "roe",
    "revenue_growth",
    "net_profit_growth",
    "debt_to_assets",
    "operating_cash_flow_quality",
    "gross_margin",
    "free_cash_flow_to_enterprise_value"
  ],
  "optimizerModes": [
    "baseline",
    "constrained"
  ],
  "pointInTimeFundamentals": true,
  "industryNeutrality": true,
  "industryAbsoluteBounds": true,
  "extensionReport": true,
  "capabilityVersion": "44ff0c9ed46f64308c8ced6f6cd021322983fe4754f1cb9b5fbfdec8cce98b36"
} as const;
